language: python
install: pip install -r requirements.txt --use-mirrors
before_script:
- psql -c 'create database civic_json_worker_test;' -U postgres
- psql -c 'create database peopledbtest;' -U postgres
- psql -c '\i test/peopledbtest.pgsql' -U postgres
script:
- green test/integration test/importer -vvv --run-coverage
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/72d031cc-8f21-4968-8db6-ff7370f5e98b/status
  slack: cfa:IjK8dNdwBJHL0Xc9FqvROliV
